/**
 * Server-side "powerful model" hamper previews.
 * Provider chain (first configured key wins):
 *   1) GEMINI_API_KEY  → Gemini image (nano-banana class) — best quality, free tier available
 *   2) OPENAI_API_KEY  → gpt-image-1
 *   3) (none)          → caller falls back to the free Pollinations URL (lib/hamper-art.ts)
 * Generated bytes are stored in Supabase Storage bucket "previews" (public) as
 * <orderId>.jpg so the order page, emails and work-orders all share one stable URL.
 * Everything is optional & silent: any failure → graceful fallback, checkout never breaks.
 */
import { apiCfg } from "@/lib/apis";
import { admin } from "@/lib/supabase";

export type ArtOpts = { names: string[]; contents?: string[]; occasion?: string; seed: string };

export function previewPublicUrl(orderId: string): string {
  return `${process.env.NEXT_PUBLIC_SUPABASE_URL}/storage/v1/object/public/previews/${orderId}.jpg`;
}

export async function storePreview(orderId: string, buf: Buffer): Promise<boolean> {
  try {
    const { error } = await admin()
      .storage.from("previews")
      .upload(`${orderId}.jpg`, buf, { contentType: "image/jpeg", upsert: true });
    return !error;
  } catch {
    return false;
  }
}

export async function previewExists(orderId: string): Promise<boolean> {
  try {
    const res = await fetch(previewPublicUrl(orderId), { method: "HEAD", signal: AbortSignal.timeout(5000) });
    return res.ok;
  } catch {
    return false;
  }
}

function promptFor(o: ArtOpts): string {
  const subject = (o.contents && o.contents.length ? o.contents : o.names).slice(0, 8).join(", ");
  return (
    `Ultra-realistic professional e-commerce product photograph, crisp focus, high detail: ` +
    `one open natural wicker gift hamper basket lined with blush pink tissue paper, ` +
    `neatly filled with clearly recognizable items: ${subject}. ` +
    (o.occasion ? `Tasteful ${o.occasion} occasion accents. ` : "") +
    `Pastel palette of blush pink, lavender, mint and butter yellow on a seamless pale cream backdrop, ` +
    `bright soft studio daylight, gentle shadow under the basket, silk ribbon bow on the handle, ` +
    `blank kraft gift tag, magazine editorial styling. ` +
    `Every item sharply rendered and identifiable. All candles unlit, no flames, no smoke, no text, no watermark, no people.`
  );
}

export async function generateHamperArt(o: ArtOpts): Promise<Buffer | null> {
  return (await viaGemini(o)) ?? (await viaOpenAI(o));
}

async function viaGemini(o: ArtOpts): Promise<Buffer | null> {
  const cfg = await apiCfg();
  const key = cfg.geminiKey;
  if (!key) return null;
  const models = [cfg.geminiModel || "gemini-2.5-flash-image", "gemini-2.5-flash-image-preview"];
  for (const m of models) {
    try {
      const res = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${m}:generateContent`, {
        method: "POST",
        headers: { "x-goog-api-key": key, "Content-Type": "application/json" },
        body: JSON.stringify({ contents: [{ role: "user", parts: [{ text: promptFor(o) }] }] }),
        signal: AbortSignal.timeout(60000),
      });
      if (!res.ok) continue;
      const j = await res.json();
      const parts: any[] = j?.candidates?.[0]?.content?.parts ?? [];
      const img = parts.find((p) => p?.inlineData?.data);
      if (img) return Buffer.from(img.inlineData.data, "base64");
    } catch {
      /* try next model */
    }
  }
  return null;
}

async function viaOpenAI(o: ArtOpts): Promise<Buffer | null> {
  const key = (await apiCfg()).openaiKey;
  if (!key) return null;
  try {
    const res = await fetch("https://api.openai.com/v1/images/generations", {
      method: "POST",
      headers: { Authorization: `Bearer ${key}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        model: (await apiCfg()).openaiModel || "gpt-image-1",
        prompt: promptFor(o),
        size: "1024x1536",
        n: 1,
      }),
      signal: AbortSignal.timeout(90000),
    });
    if (!res.ok) return null;
    const j = await res.json();
    const b64 = j?.data?.[0]?.b64_json;
    return b64 ? Buffer.from(b64, "base64") : null;
  } catch {
    return null;
  }
}
